CREATE TABLE PLAYERS(
	PLAYER_ID INT(11) NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(100) NOT NULL,
	lastName VARCHAR(100) NOT NULL,
	PRIMARY KEY(PLAYER_ID)
);

CREATE TABLE GameCharacter(
	CHARACTER_ID INT(11) NOT NULL AUTO_INCREMENT,
	CHARACTER_CLASS VARCHAR(100) NOT NULL,
	CHARACTER_NAME VARCHAR(100) NOT NULL,
	CHARACTER_GENDER VARCHAR(100) NOT NULL,
	CHARACTER_KUBITS INT(11) NOT NULL,
	CHARACTER_INVENTORY_ID INT(11) NOT NULL,
	PRIMARY KEY (CHARACTER_ID)
);

CREATE TABLE inventory(
	INVENTORY_ID INT(11) NOT NULL AUTO_INCREMENT,
	UP_CLOSE INT(11) NOT NULL DEFAULT 0,
	DISTANCE INT(11) NOT NULL DEFAULT 0,
	SHIELD INT(11) NOT NULL DEFAULT 0,
	ARMOUR INT(11) NOT NULL DEFAULT 0,
	PRIMARY KEY (INVENTORY_ID)
);


CREATE TABLE items(
	INVENTORY_ID INT(100) NOT NULL,
	ITEM_ID INT(100) NOT NULL AUTO_INCREMENT,
	ITEM VARCHAR(100) NOT NULL,
	EQUIP_TYPE VARCHAR(100) NOT NULL,
	PROTECTION INT(100) NOT NULL,
	DAMAGE INT(100) NOT NULL,
	PURCHASE_COST INT(100) NOT NULL,
	SELL_VALUE INT(100) NOT NULL,
	UPGRADE_COST INT(100) NOT NULL,
	PRIMARY KEY (ITEM_ID,INVENTORY_ID)
);

CREATE TABLE PLAYERS_GAME_STATE(
	PLAYER_ID INT(11) NOT NULL,
	CHARACTER_ID INT(11) NOT NULL,
	INVENTORY_ID INT(11) NOT NULL,
	PRIMARY KEY (PLAYER_ID,CHARACTER_ID,INVENTORY_ID)
);